services:
  application:
    build:
      context: .
      dockerfile: docker/Dockerfile
      network: host
    container_name: application
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - db_volume:/app/db
    working_dir: /app
    command: >
      bash -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_volume: